sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^v?[0-9\\.]+$/"

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - WP_VERSION=latest
  - WP_VERSION=trunk

install:
  - composer self-update
  - composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - vendor/bin/phpunit
